### ISSUE TITLE
[BUG] 'Runtime' object has no attribute 'is_supported_version'

### ISSUE THREAD

**Issue by chtruong814** [NVIDIA/numba-cuda#570]
**Describe the bug**
Encountered this error when calling `cuda.is_supported_version()`

```
>>> cuda.is_supported_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.12/site-packages/numba_cuda/numba/cuda/device_init.py", line 133, in is_supported_version
    return runtime.is_supported_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Runtime' object has no attribute 'is_supported_version'
```

**Steps/Code to reproduce bug**
* numba-cuda version 0.20.1
```
from numba import cuda

cuda.is_supported_version()
```

**Expected behavior**
This should return a boolean with whether the cuda version is supported by numba. 

**Additional context**

**Comment by kkraus14** [comment]
Looks like this got broken in https://github.com/NVIDIA/numba-cuda/pull/313 cc @gmarkall

**Comment by gmarkall** [comment]
I'm looking into this now.

**Comment by gmarkall** [comment]
Fix proposed in #571.
